plugins:
  - "@typescript-eslint/eslint-plugin"
extends:
  - prettier
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  sourceType: 'module'
root: true
env:
  node: true
rules:
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
